site_name: Bashgenn DOCS
repo_url: https://github.com/romw314/bashgenn-docs
markdown_extensions:
  - attr_list
extra_css:
  - style.css
nav:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
